/* MSC Traceability v3: plan baseline, quantity variance, and Finished Good authority. */
(function(){
  const KEY='msc-traceability-v3', SESSION='msc-session-v3';
  const users=[
    ['planner','planner','Rina Planner','PLANNER','PPIC'],['warehouse','warehouse','Doni Warehouse','WAREHOUSE','Warehouse'],
    ['prepare','prepare','Sari Prepare','PREPARE','Material Prepare'],['mca','mca','Bima MC A','MC_A','Production'],
    ['mcb','mcb','Citra MC B','MC_B','Production'],['mcc','mcc','Dewa MC C','MC_C','Production'],
    ['quality','quality','Nina Quality','QUALITY','Final Inspection'],['fg','fg','Fajar Finished Good','FINISHED_GOODS','Finished Good'],
    ['incoming','incoming','Maya Incoming','CUSTOMER_INCOMING','Customer Incoming'],['admin','admin','Adit Admin','ADMIN','System Control']
  ].map(function(x){return {id:x[0],username:x[1],password:'demo123',name:x[2],role:x[3],dept:x[4]};});
  const roleName={PLANNER:'Planner / PPIC',WAREHOUSE:'Warehouse PIC',PREPARE:'Prepare PIC',MC_A:'Operator MC A',MC_B:'Operator MC B',MC_C:'Operator MC C',QUALITY:'Final Inspection',FINISHED_GOODS:'Finished Good PIC',CUSTOMER_INCOMING:'Customer Incoming',ADMIN:'Admin'};
  const catalog=[['A-LED-001','Smart Headlamp Module'],['B-CAM-002','Camera Housing Module'],['C-LENS-003','Lens Assembly']];
  const stages=[
    ['PLAN_RELEASED','Plan Released','PLANNER','plan'],['MATERIAL_REQUESTED','Raw Material Request','PLANNER','part'],
    ['RAW_MATERIAL_RECEIVED','Raw Material Received','WAREHOUSE','part'],['MATERIAL_PREPARED','Material Prepared','PREPARE','part'],
    ['MC_A_COMPLETE','MC A Complete','MC_A','part'],['MC_B_COMPLETE','MC B Complete','MC_B','part'],
    ['MC_C_COMPLETE','MC C Complete','MC_C','part'],['FINAL_INSPECTION_PASS','Final Inspection Pass','QUALITY','part'],
    ['FINISHED_GOODS_RECEIVED','Finished Good Received','FINISHED_GOODS','part'],['DN_GENERATED','Delivery Note Generated','FINISHED_GOODS','dn'],
    ['SHIPMENT_SENT','Shipment Sent','FINISHED_GOODS','dn'],['CUSTOMER_RECEIVED','Customer Received','CUSTOMER_INCOMING','dn']
  ];
  const qtyStages=['MC_A_COMPLETE','MC_B_COMPLETE','MC_C_COMPLETE','FINAL_INSPECTION_PASS','FINISHED_GOODS_RECEIVED'];
  let app=document.getElementById('app'), state=load(), session=JSON.parse(localStorage.getItem(SESSION)||'null'), page='flow', stream=null;
  function seed(){return {order:{planNo:'PLAN-2026-091',partId:'A-LED-001',partName:'Smart Headlamp Module',lotId:'LOT-2409-A',planQty:200,availableQty:200,unit:'pcs',dnCode:'DN-2409-001',cursor:0,attempts:null,lock:null},events:[]};}
  function load(){try{let x=JSON.parse(localStorage.getItem(KEY));return x&&x.order&&x.events?x:seed();}catch(e){return seed();}}
  function save(){localStorage.setItem(KEY,JSON.stringify(state));}
  function me(){return users.find(function(u){return session&&u.id===session.id;});}
  function stage(){return stages[state.order.cursor];}
  function esc(x){return String(x==null?'':x).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function expected(s){return s[3]==='plan'?state.order.planNo:s[3]==='part'?state.order.partId+'|'+state.order.lotId:state.order.dnCode;}
  function log(type,message,data){let u=me()||{name:'System',role:'SYSTEM',dept:'System'};state.events.push(Object.assign({type:type,message:message,at:new Date().toISOString(),pic:u.name,role:u.role,dept:u.dept,partId:state.order.partId,lotId:state.order.lotId,planQty:state.order.planQty,actualQty:state.order.availableQty,variance:state.order.planQty-state.order.availableQty},data||{}));save();}
  function fmt(x){return new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(x));}
  function login(name,password){let u=users.find(function(x){return x.username===name&&x.password===password;});if(!u)return pop('bad','Login rejected','Username atau password demo tidak sesuai.');session={id:u.id};localStorage.setItem(SESSION,JSON.stringify(session));page='flow';render();}
  function logout(){session=null;localStorage.removeItem(SESSION);render();}
  function reset(){state=seed();save();render();}
  function render(){let u=me();if(!u)return renderLogin();let s=stage();app.innerHTML='<div class="app-shell"><aside class="sidebar"><div class="logo">MSC Trace<small>VERIFIED HANDOFF POC</small></div><div class="profile"><b>'+esc(u.name)+'</b><span>'+esc(roleName[u.role])+' · '+esc(u.dept)+'</span></div><nav class="nav"><button data-v3-page="flow" class="'+(page==='flow'?'active':'')+'">Traceability Flow</button><button data-v3-page="task" class="'+(page==='task'?'active':'')+'">My Transaction</button>'+(u.role==='ADMIN'?'<button data-v3-page="report" class="'+(page==='report'?'active':'')+'">Report & Recovery</button>':'')+'</nav><div class="side-bottom"><button data-v3="reset">Reset Demo</button><button data-v3="logout">Keluar</button></div></aside><main class="main"><header class="topbar"><div><h1>'+ (page==='task'?'My Transaction':page==='report'?'Report & Recovery':'Traceability Flow')+'</h1><p>Plan baseline, actual quantity, reason, and PIC evidence</p></div>'+status()+'</header><section class="content">'+(page==='task'?task():page==='report'?report():flow())+'</section></main></div>';}
  function status(){if(state.order.lock)return '<span class="status red">! LOCKED</span>';if(!stage())return '<span class="status green">✓ CUSTOMER RECEIVED</span>';return '<span class="status blue">• '+esc(stage()[1])+'</span>';}
  function renderLogin(){app.innerHTML='<main class="login"><section class="login-card"><div class="brand"><div class="eyebrow">After Project · MSC</div><h1>Trace the real handoff.</h1><p>Plan quantity becomes the baseline. Every loss or NG needs a reason.</p></div><div class="login-form"><h2>Demo PIC Login</h2><form id="v3Login"><div class="field"><label>Username</label><input name="username" required></div><div class="field"><label>Password</label><input name="password" type="password" required></div><button class="button wide">Masuk</button></form><div class="demo-users">'+users.map(function(u){return '<button data-v3-user="'+u.username+'"><b>'+esc(roleName[u.role])+'</b><small>'+u.username+' / demo123</small></button>';}).join('')+'</div></div></section></main>';}
  function facts(){let o=state.order;return '<div class="facts"><div class="fact"><small>Plan</small><b>'+esc(o.planNo)+'</b></div><div class="fact"><small>Part / Lot</small><b>'+esc(o.partId)+' · '+esc(o.lotId)+'</b></div><div class="fact"><small>Plan Qty</small><b>'+o.planQty+' pcs</b></div><div class="fact"><small>Available Actual</small><b>'+o.availableQty+' pcs</b></div><div class="fact"><small>Variance</small><b>'+ (o.planQty-o.availableQty)+' pcs</b></div><div class="fact"><small>DN</small><b>'+esc(o.dnCode)+'</b></div></div>';}
  function flow(){let cur=stage();return '<article class="card"><div class="order-head"><div><div class="role-label">Plan baseline</div><h2>'+esc(state.order.partName)+'</h2><p class="muted">Expected Part/Lot barcode: <b>'+esc(state.order.partId+'|'+state.order.lotId)+'</b></p></div>'+status()+'</div>'+facts()+'</article><div class="grid two" style="margin-top:18px"><article class="card"><h2>Process evidence</h2><ol class="timeline">'+stages.map(function(x,i){let done=i<state.order.cursor,now=i===state.order.cursor;let e=state.events.filter(function(z){return z.type===x[0];}).slice(-1)[0];return '<li><span class="dot '+(done?'good':now?'admin':'')+'"></span><div><b>'+esc(x[1])+'</b><small>PIC: '+esc(roleName[x[2]])+'</small></div><time>'+ (e?fmt(e.at):(now?'Waiting':'Locked by sequence'))+'</time></li>';}).join('')+'</ol></article><aside class="card"><div class="role-label">Critical quantity control</div><h2>'+esc(cur?cur[1]:'Flow complete')+'</h2><p class="muted">Qty decrease is not hidden: the PIC must select a reason, and the variance remains in the audit report.</p>'+(state.order.lock?'<div class="notice bad"><b>Admin review required</b><p>'+esc(state.order.lock.reason)+'</p></div>':'<div class="notice good"><b>Current owner</b><p>'+esc(cur?roleName[cur[2]]:'Completed')+'</p></div>')+'</aside></div>';}
  function planFields(){let opts=catalog.map(function(p){return '<option value="'+p[0]+'" '+(p[0]===state.order.partId?'selected':'')+'>'+p[0]+' — '+p[1]+'</option>';}).join('');return '<div class="field"><label>Part to plan</label><select id="v3Part">'+opts+'</select></div><div class="field"><label>Plan Quantity (pcs)</label><input id="v3PlanQty" type="number" min="1" value="'+state.order.planQty+'"></div><button class="button secondary" data-v3="save-plan">Save Plan Baseline</button>';}
  function qtyFields(s){if(qtyStages.indexOf(s[0])<0)return '';let reason=['','Production NG','Material shortage from Prepare','Machine stop / damage','Final inspection reject','Other approved reason'];return '<div class="field"><label>Actual quantity accepted at this stage</label><input id="v3ActualQty" type="number" min="0" max="'+state.order.availableQty+'" value="'+state.order.availableQty+'"></div><div class="field"><label>Reason (required only when qty decreases)</label><select id="v3Reason">'+reason.map(function(x){return '<option value="'+x+'">'+(x||'Select reason')+'</option>';}).join('')+'</select></div>';}
  function task(){let u=me(),s=stage();if(!s)return '<article class="card"><h2>Customer Received completed</h2><p>DN cannot be processed a second time.</p></article>';if(state.order.lock)return '<article class="card"><div class="notice bad"><b>Flow locked</b><p>'+esc(state.order.lock.reason)+'</p></div><p>Only Admin can unlock after documenting a recovery reason.</p></article>';if(u.role!==s[2])return '<article class="card"><div class="notice bad"><b>Step cannot be skipped</b><p>Waiting for '+esc(roleName[s[2]])+' to complete '+esc(s[1])+'.</p></div></article>';return '<article class="card"><div class="role-label">Authorised PIC transaction</div><h2>'+esc(s[1])+'</h2><p class="muted">Expected scan: <b>'+esc(expected(s))+'</b></p>'+facts()+(s[0]==='PLAN_RELEASED'?planFields():'')+qtyFields(s)+'<div class="receipt-gate"><div class="gate-row"><b>Retry protection</b><span>'+((state.order.attempts&&state.order.attempts.step===s[0])?state.order.attempts.count:0)+' / 3 attempts</span></div></div><div class="actions"><button class="button" data-v3="scan-camera">Scan with camera</button><button class="button secondary" data-v3="scan-demo">Run marked demo scan</button></div></article>';}
  function savePlan(){let id=document.getElementById('v3Part').value,qty=Number(document.getElementById('v3PlanQty').value),p=catalog.find(function(x){return x[0]===id;});if(!p||!Number.isInteger(qty)||qty<1)return pop('bad','Plan rejected','Select a part and a positive quantity.');let o=state.order;o.partId=p[0];o.partName=p[1];o.planQty=qty;o.availableQty=qty;o.lotId='LOT-'+String(Date.now()).slice(-6);o.dnCode='DN-'+String(Date.now()).slice(-6);log('PLAN_CONFIGURED','Part and quantity baseline configured',{reason:'Plan baseline'});render();pop('good','Plan baseline saved',p[0]+' planned at '+qty+' pcs.');}
  function validateQty(s){if(qtyStages.indexOf(s[0])<0)return {actual:state.order.availableQty,reason:''};let qty=Number(document.getElementById('v3ActualQty').value),reason=document.getElementById('v3Reason').value,available=state.order.availableQty;if(!Number.isInteger(qty)||qty<0)return {error:'Actual quantity must be a whole number.'};if(qty>available)return {error:'Actual quantity cannot exceed available '+available+' pcs.'};if(qty<available&&!reason)return {error:'A reason is required because actual qty is lower than the previous stage.'};return {actual:qty,reason:reason};}
  function scan(value,source){let s=stage(),u=me();if(!s||u.role!==s[2])return pop('bad','Step flow rejected','This PIC cannot execute the active transaction.');if(value!==expected(s))return reject('Barcode does not match expected '+expected(s)+'.',{scanSource:source});let q=validateQty(s);if(q.error)return reject(q.error,{scanSource:source});complete(s,source,q);}
  function complete(s,source,q){if(qtyStages.indexOf(s[0])>=0){state.order.availableQty=q.actual;}let variance=state.order.planQty-state.order.availableQty;log(s[0],s[1]+' confirmed',{scanSource:source,actualQty:state.order.availableQty,variance:variance,reason:q.reason||''});state.order.cursor++;state.order.attempts=null;save();render();pop('good','Transaction successful',s[1]+' recorded. Plan '+state.order.planQty+' pcs, actual '+state.order.availableQty+' pcs, variance '+variance+' pcs.');}
  function reject(reason,extra){let s=stage(),prior=(state.order.attempts&&state.order.attempts.step===s[0])?state.order.attempts.count:0,count=prior+1;state.order.attempts={step:s[0],count:count};if(count<3){log('SCAN_REJECTED','Scan rejected — retry allowed',Object.assign({reason:reason,attempt:count},extra||{}));save();render();return pop('bad','Scan rejected — '+count+'/3',reason+' You can retry '+(3-count)+' time(s).');}state.order.lock={step:s[0],reason:reason};log('ABNORMALITY_LOCK','Flow locked after 3 rejected scans',Object.assign({reason:reason,attempt:count},extra||{}));save();render();pop('bad','Flow locked',reason+' Admin review is required.');}
  function report(){if(me().role!=='ADMIN')return '<article class="card">Admin only.</article>';let lock=state.order.lock;return '<article class="card"><div class="order-head"><div><div class="role-label">Evidence & variance report</div><h2>Traceability audit</h2></div><button class="button" data-v3="export">Download CSV</button></div>'+(lock?'<div class="notice bad"><b>'+esc(lock.step)+'</b><p>'+esc(lock.reason)+'</p><textarea id="v3UnlockReason" placeholder="Recovery reason is required"></textarea><button class="button" data-v3="unlock">Unlock for re-scan</button></div>':'')+'<div class="table-wrap"><table class="report-table"><thead><tr><th>Time</th><th>Event</th><th>PIC</th><th>Plan</th><th>Actual</th><th>Variance</th><th>Reason</th></tr></thead><tbody>'+state.events.slice().reverse().map(function(e){return '<tr><td>'+fmt(e.at)+'</td><td>'+esc(e.type)+'</td><td>'+esc(e.pic)+'</td><td>'+e.planQty+'</td><td>'+e.actualQty+'</td><td>'+e.variance+'</td><td>'+esc(e.reason||'—')+'</td></tr>';}).join('')+'</tbody></table></div></article>';}
  function unlock(){let r=document.getElementById('v3UnlockReason').value.trim();if(!r)return pop('bad','Reason required','Admin must document why the PIC may retry.');log('ADMIN_UNLOCK','Admin unlocked flow',{reason:r});state.order.lock=null;state.order.attempts=null;save();render();pop('good','Flow unlocked','The assigned PIC must scan again.');}
  function camera(){let s=stage();if(!('BarcodeDetector'in window)||!navigator.mediaDevices)return reject('Camera scanner is not available in this browser.',{});let d=document.getElementById('cameraDialog');d.querySelector('strong').textContent='Scan '+s[1];d.showModal();navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}}).then(function(x){stream=x;let v=document.getElementById('cameraPreview');v.srcObject=x;let detector=new BarcodeDetector({formats:['qr_code','code_128','code_39']});function loop(){if(!stream)return;detector.detect(v).then(function(c){if(c[0]){stopCamera();scan(c[0].rawValue,'camera');}else requestAnimationFrame(loop);}).catch(function(){requestAnimationFrame(loop);});}loop();}).catch(function(e){reject('Camera permission denied or failed.',{});});}
  function stopCamera(){if(stream){stream.getTracks().forEach(function(t){t.stop();});stream=null;}let d=document.getElementById('cameraDialog');if(d.open)d.close();}
  function csv(){let h=['time','event','pic','role','part','lot','plan_qty','actual_qty','variance','reason','scan_source'];let r=state.events.map(function(e){return [e.at,e.type,e.pic,e.role,e.partId,e.lotId,e.planQty,e.actualQty,e.variance,e.reason||'',e.scanSource||''];});return [h].concat(r).map(function(x){return x.map(function(v){return '"'+String(v).replaceAll('"','""')+'"';}).join(',');}).join('\n');}
  function exportCsv(){let a=document.createElement('a'),url=URL.createObjectURL(new Blob([csv()],{type:'text/csv'}));a.href=url;a.download='MSC_Traceability_Audit.csv';a.click();URL.revokeObjectURL(url);}
  function pop(t,title,msg){let d=document.getElementById('v3Popup');if(!d){d=document.createElement('dialog');d.id='v3Popup';d.className='result-dialog';document.body.append(d);}d.innerHTML='<section class="result-card '+(t==='good'?'success':'reject')+'"><div class="result-icon">'+(t==='good'?'✓':'!')+'</div><h2>'+esc(title)+'</h2><p>'+esc(msg)+'</p><button class="button" data-v3="close">Mengerti</button></section>';d.showModal();}
  document.addEventListener('submit',function(e){if(e.target.id==='v3Login'){e.preventDefault();let f=new FormData(e.target);login(f.get('username'),f.get('password'));}});
  document.addEventListener('click',function(e){let b=e.target.closest('button');if(!b)return;if(b.dataset.v3Page){page=b.dataset.v3Page;render();return;}if(b.dataset.v3User)return login(b.dataset.v3User,'demo123');let a=b.dataset.v3;if(a==='logout')logout();if(a==='reset')reset();if(a==='save-plan')savePlan();if(a==='scan-demo')scan(expected(stage()),'demo-simulation');if(a==='scan-camera')camera();if(a==='unlock')unlock();if(a==='export')exportCsv();if(a==='close'){let d=document.getElementById('v3Popup');if(d)d.close();}});
  render();
})();