/* MSC Traceability POC — browser-local demonstration data, not a production audit system. */
(function () {
  const STORAGE = 'msc-traceability-poc-v1';
  const SESSION = 'msc-traceability-session-v1';
  const users = [
    { id: 'u-planner', username: 'planner', password: 'demo123', name: 'Rina Planner', role: 'PLANNER', department: 'PPIC' },
    { id: 'u-wh', username: 'warehouse', password: 'demo123', name: 'Doni Warehouse', role: 'WAREHOUSE', department: 'Warehouse' },
    { id: 'u-customer', username: 'incoming', password: 'demo123', name: 'Maya Incoming', role: 'CUSTOMER_INCOMING', department: 'Customer Incoming', customerId: 'cus-01' },
    { id: 'u-admin', username: 'admin', password: 'demo123', name: 'Adit Admin', role: 'ADMIN', department: 'System Control' }
  ];
  const seed = () => ({
    order: { id: 'ord-001', planNo: 'PLAN-2026-091', partId: 'A-LED-001', partName: 'Smart Headlamp Module', lotId: 'LOT-2409-A', quantity: 120, unit: 'pcs', customerId: 'cus-01', customerName: 'SEMV Demo Plant', dnCode: 'DN-2409-001', status: 'SHIPMENT', warehouseState: 'SENT', receiptLock: null },
    customer: { id: 'cus-01', name: 'SEMV Demo Plant', latitude: -6.3764484, longitude: 107.3181421, radiusMeters: 250 },
    events: [
      event('PLAN_CREATED', 'Plan released', users[0], { demoSeed: true }),
      event('MATERIAL_PREPARED', 'Material prepared', users[1], { demoSeed: true }),
      event('PROCESS_COMPLETE', 'MC A → MC C → Final Inspection completed', users[0], { demoSeed: true }),
      event('FG_RELEASED', 'Finished goods released', users[1], { demoSeed: true }),
      event('DN_RELEASED', 'Delivery Note released', users[0], { demoSeed: true }),
      event('SHIPMENT_SENT', 'Shipment dispatched to customer', users[1], { demoSeed: true })
    ],
    notifications: []
  });
  function event(type, message, actor, extras = {}) { return { id: cryptoId(), type, message, orderId: 'ord-001', dnCode: 'DN-2409-001', actorId: actor.id, actorName: actor.name, role: actor.role, department: actor.department, at: new Date().toISOString(), quantity: 120, ...extras }; }
  function cryptoId() { return (globalThis.crypto && crypto.randomUUID) ? crypto.randomUUID() : `evt-${Date.now()}-${Math.random().toString(16).slice(2)}`; }
  function load() { try { const x = JSON.parse(localStorage.getItem(STORAGE)); return x && x.order && Array.isArray(x.events) ? x : seed(); } catch { return seed(); } }
  function save(data) { localStorage.setItem(STORAGE, JSON.stringify(data)); return data; }
  let state = load();
  let session = JSON.parse(localStorage.getItem(SESSION) || 'null');
  let page = 'tracking';
  let stream = null;
  const app = document.getElementById('app');
  const roleNames = { PLANNER: 'Planner', WAREHOUSE: 'Warehouse PIC', CUSTOMER_INCOMING: 'Customer Incoming', ADMIN: 'Admin' };
  const allowed = { PLANNER: ['tracking'], WAREHOUSE: ['warehouse','tracking'], CUSTOMER_INCOMING: ['incoming','tracking'], ADMIN: ['tracking','warehouse','incoming','admin','report'] };
  function me() { return users.find(u => u.id === session?.userId) || null; }
  function requireRole(...roles) { const u = me(); if (!u || !roles.includes(u.role)) throw new Error('Akses ditolak untuk role ini.'); return u; }
  function addEvent(type, message, extras = {}) { const u = me(); state.events.push(event(type, message, u, extras)); save(state); }
  function login(username, password) { const user = users.find(u => u.username === username && u.password === password); if (!user) return toast('Username atau password demo tidak cocok.'); session = { userId: user.id }; localStorage.setItem(SESSION, JSON.stringify(session)); page = allowed[user.role][0]; render(); }
  function logout() { session = null; localStorage.removeItem(SESSION); render(); }
  function reset() { if (!confirm('Reset seluruh transaksi POC pada browser ini?')) return; state = seed(); save(state); toast('Data demo dipulihkan.'); render(); }
  function statusBadge() { const o = state.order; if (o.receiptLock) return badge('LOCKED', 'red'); if (o.status === 'CUSTOMER_RECEIVED') return badge('CUSTOMER RECEIVED', 'green'); return badge('SHIPMENT', 'blue'); }
  function badge(text, tone='blue') { return `<span class="status ${tone}">${tone==='red'?'!':tone==='green'?'✓':'•'} ${esc(text)}</span>`; }
  function esc(value) { return String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
  function fmt(iso) { return new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(iso)); }
  function render() { const user = me(); if (!user) return renderLogin(); if (!allowed[user.role].includes(page)) page = allowed[user.role][0]; app.innerHTML = `<div class="app-shell"><aside class="sidebar"><div class="logo">MSC Trace<small>PROOF OF CONCEPT</small></div><div class="profile"><b>${esc(user.name)}</b><span>${esc(roleNames[user.role])} · ${esc(user.department)}</span></div><nav class="nav">${nav(user)}</nav><div class="side-bottom"><button data-action="logout">Keluar</button></div></aside><main class="main"><header class="topbar"><div><h1>${title()}</h1><p>${esc(user.name)} · ${esc(roleNames[user.role])}</p></div>${statusBadge()}</header><section class="content">${view()}</section></main></div>`; }
  function nav(user) { const items = [{id:'tracking',label:'Order Tracking'},{id:'warehouse',label:'Warehouse'},{id:'incoming',label:'Incoming DN'},{id:'admin',label:'Abnormality & Recovery'},{id:'report',label:'Report CSV'}]; return items.filter(x=>allowed[user.role].includes(x.id)).map(x=>`<button class="${page===x.id?'active':''}" data-page="${x.id}">${x.label}</button>`).join(''); }
  function title() { return ({tracking:'Order Tracking',warehouse:'Warehouse Handoff',incoming:'Incoming Customer Receipt',admin:'Abnormality & Recovery',report:'Report Evidence'})[page]; }
  function renderLogin() { app.innerHTML = `<main class="login"><section class="login-card"><div class="brand"><div class="eyebrow">After Project · MSC</div><h1>Trace the proof.</h1><p>Jejak part dari plan sampai customer received, dengan PIC, waktu, lokasi, dan abnormality yang terlihat.</p><p><small>POC demo · Data tersimpan hanya pada browser ini.</small></p></div><div class="login-form"><h2>Masuk sebagai PIC</h2><p class="muted">Gunakan salah satu akun demo untuk melihat otoritas berbeda.</p><form id="loginForm"><div class="field"><label>Username</label><input name="username" autocomplete="username" required></div><div class="field"><label>Password</label><input name="password" type="password" autocomplete="current-password" required></div><button class="button wide">Masuk</button></form><div class="demo-users">${users.map(u=>`<button data-demo-user="${u.username}"><b>${esc(roleNames[u.role])}</b><small>${esc(u.username)} / demo123</small></button>`).join('')}</div><div class="actions"><button class="button secondary" data-action="reset">Reset demo data</button></div></div></section></main>`; }
  function view() { if (page==='warehouse') return warehouseView(); if (page==='incoming') return incomingView(); if (page==='admin') return adminView(); if (page==='report') return reportView(); return trackingView(); }
  function trackingView() { const o=state.order; return `<div class="grid three"><article class="card metric"><span>Current status</span><b>${esc(o.status.replace('_',' '))}</b>${o.receiptLock?badge('Receipt locked','red'):badge('Ready for customer proof','green')}</article><article class="card metric"><span>Traceability identity</span><b class="order-code">${esc(o.dnCode)}</b><span>${esc(o.partId)} · ${esc(o.lotId)}</span></article><article class="card metric"><span>Quantity</span><b>${o.quantity} ${esc(o.unit)}</b><span>One planned shipment</span></article></div><div class="grid two" style="margin-top:18px"><article class="card">${orderSummary()}<h3 style="margin-top:22px">Transaction history</h3>${timeline()}</article><aside class="grid"><article class="card"><div class="role-label">Traceability control</div><h2>Final receipt requires proof</h2><p class="muted">Customer Incoming must scan DN and pass camera plus location verification.</p>${o.receiptLock?`<div class="notice bad"><b>Receipt locked</b><p>${esc(o.receiptLock.reason)}</p></div>`:`<div class="notice good"><b>No active receipt lock</b><p>Shipment is waiting for customer receipt.</p></div>`}</article>${plannerNotifications()}</aside></div>`; }
  function orderSummary() { const o=state.order; return `<div class="order-head"><div><div class="order-code">${esc(o.planNo)} · ${esc(o.dnCode)}</div><h2>${esc(o.partName)}</h2></div>${statusBadge()}</div><div class="facts"><div class="fact"><small>Part ID</small><b>${esc(o.partId)}</b></div><div class="fact"><small>LOT</small><b>${esc(o.lotId)}</b></div><div class="fact"><small>Qty</small><b>${o.quantity} ${esc(o.unit)}</b></div><div class="fact"><small>Customer</small><b>${esc(o.customerName)}</b></div></div>`; }
  function timeline() { return `<ol class="timeline">${[...state.events].reverse().map(e=>{const tone=e.type.includes('LOCK')||e.type.includes('REJECT')?'bad':e.type.includes('UNLOCK')?'admin':'good';return `<li><span class="dot ${tone}"></span><div><b>${esc(e.message)}</b><small>${esc(e.actorName)} · ${esc(roleNames[e.role]||e.role)} · ${esc(e.department)}${e.reason?` · ${esc(e.reason)}`:''}</small></div><time>${fmt(e.at)}</time></li>`}).join('')}</ol>`; }
  function plannerNotifications() { const notes=state.notifications; return `<article class="card"><div class="role-label">Planner notification</div><h2>Receipt updates</h2>${notes.length?notes.map(n=>`<div class="notice good"><b>${esc(n.title)}</b><p>${esc(n.message)}</p></div>`).join(''):`<div class="empty">Belum ada Customer Received yang sah.</div>`}</article>`; }
  function warehouseView() { const o=state.order; const u=me(); const can=requireRole('WAREHOUSE','ADMIN'); return `<div class="grid two"><article class="card">${orderSummary()}<div class="notice ${o.warehouseState==='SENT'?'good':'amber'}"><b>Warehouse state: ${esc(o.warehouseState)}</b><p>Hanya Warehouse/Admin dapat mencatat handoff pada tahap ini.</p></div><div class="actions">${o.warehouseState==='READY'?`<button class="button" data-action="warehouse-received">Record Warehouse Received</button>`:''}${o.warehouseState==='RECEIVED'?`<button class="button" data-action="warehouse-sent">Record Warehouse Sent</button>`:''}${o.warehouseState==='SENT'?`<span class="status green">✓ Handoff complete</span>`:''}</div></article><article class="card"><div class="role-label">Authority check</div><h2>${esc(u.name)}</h2><ul><li>Can record: Warehouse Received/Sent</li><li>Cannot: Customer receipt</li><li>Cannot: Admin recovery</li></ul><div class="notice amber"><b>Duplicate protection</b><p>Action only appears in the next valid warehouse state.</p></div></article></div><article class="card" style="margin-top:18px"><h2>Timeline</h2>${timeline()}</article>`; }
  function incomingView() { const o=state.order; const isIncoming=me().role==='CUSTOMER_INCOMING'; const accessNotice=!isIncoming?`<div class="notice amber"><b>Read-only for Admin</b><p>Admin may inspect receipt evidence but cannot scan or confirm Customer Received. Only Customer Incoming may perform this transaction.</p></div>`:''; return `<div class="grid two"><article class="card">${orderSummary()}${accessNotice}${o.receiptLock?`<div class="notice bad"><b>DN locked</b><p>${esc(o.receiptLock.reason)}. Ask Admin to review and unlock. Status shipment stays unchanged.</p></div>`:isIncoming?incomingControls():''}<h3 style="margin-top:20px">Related history</h3>${timeline()}</article><aside class="card"><div class="role-label">Why this is controlled</div><h2>Customer proof</h2><p class="muted">No text field can produce Customer Received. The browser must open the camera, recognize the DN, and collect a current location.</p><div class="notice amber"><b>Demo data</b><p>Customer coordinate is a safe sample coordinate. Do not treat it as a real customer geofence.</p></div></aside></div>`; }
  function incomingControls() { const o=state.order; if(o.status==='CUSTOMER_RECEIVED')return `<div class="notice good"><b>Already received</b><p>This DN was accepted previously. Scan again cannot create a second receipt.</p></div>`; if(o.status!=='SHIPMENT')return `<div class="notice amber"><b>Not ready</b><p>DN must be in Shipment before Customer Received.</p></div>`; return `<div class="receipt-gate"><div class="gate-row"><b>1. DN barcode</b><span id="scanGate">Not scanned</span></div><div class="gate-row"><b>2. Device location</b><span id="locationGate">Not checked</span></div><div class="gate-row"><b>3. Verify and confirm</b><span id="confirmGate">Waiting</span></div></div><div class="actions"><button class="button" data-action="open-camera">Scan DN with camera</button><button class="button secondary" data-action="demo-scan">Use marked demo scan</button></div><p class="muted"><small>Demo scan is visibly marked as simulation and only tests the workflow; it never claims a real camera scan.</small></p>`; }
  function adminView() { requireRole('ADMIN'); const o=state.order; return `<div class="grid two"><article class="card"><div class="role-label">Receipt control</div><h2>${o.receiptLock?'Review locked DN':'No active lock'}</h2>${o.receiptLock?`<div class="notice bad"><b>${esc(o.dnCode)} locked</b><p>${esc(o.receiptLock.reason)} · ${fmt(o.receiptLock.lockedAt)}</p></div><div class="field"><label>Recovery reason (required)</label><textarea id="recoveryReason" rows="3" placeholder="Explain why customer may retry verification"></textarea></div><button class="button" data-action="unlock">Unlock for re-verification</button>`:`<div class="empty">No DN requires recovery. Rejected attempts will appear here.</div>`}</article><article class="card"><div class="role-label">Admin boundary</div><h2>Unlock is not receipt</h2><p class="muted">Admin only removes the lock after recording a reason. Incoming customer must still scan DN and pass camera/location checks.</p><div class="notice amber"><b>Audit trail stays visible</b><p>Lock and unlock appear in timeline and CSV.</p></div></article></div><article class="card" style="margin-top:18px"><h2>Abnormality history</h2>${timeline()}</article>`; }
  function reportView() { requireRole('ADMIN'); return `<article class="card"><div class="order-head"><div><div class="role-label">Evidence export</div><h2>Transaction Report</h2><p class="muted">Successful, rejected, and recovery events for the demo order.</p></div><button class="button" data-action="export">Download CSV</button></div><div class="table-wrap"><table class="report-table"><thead><tr><th>Time</th><th>Event</th><th>PIC</th><th>Role</th><th>Reason</th></tr></thead><tbody>${[...state.events].reverse().map(e=>`<tr><td>${fmt(e.at)}</td><td>${esc(e.type)}</td><td>${esc(e.actorName)}</td><td>${esc(roleNames[e.role]||e.role)}</td><td>${esc(e.reason||'—')}</td></tr>`).join('')}</tbody></table></div></article>`; }
  function warehouseAction(kind) { requireRole('WAREHOUSE','ADMIN'); const o=state.order; if(kind==='received'&&o.warehouseState!=='READY')return toast('Warehouse Received tidak tersedia pada state ini.'); if(kind==='sent'&&o.warehouseState!=='RECEIVED')return toast('Warehouse Sent tidak tersedia pada state ini.'); o.warehouseState=kind==='received'?'RECEIVED':'SENT'; addEvent(kind==='received'?'WAREHOUSE_RECEIVED':'WAREHOUSE_SENT',`Warehouse ${kind==='received'?'received':'sent'} material`); toast('Handoff Warehouse tercatat.'); render(); }
  function toast(message) { document.querySelector('.toast')?.remove(); const x=document.createElement('div');x.className='toast';x.textContent=message;document.body.append(x);setTimeout(()=>x.remove(),3600); }
  document.addEventListener('submit', e=>{if(e.target.id==='loginForm'){e.preventDefault();const f=new FormData(e.target);login(f.get('username'),f.get('password'));}});
  document.addEventListener('click', e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.page){page=t.dataset.page;return render();}if(t.dataset.demoUser)return login(t.dataset.demoUser,'demo123');const a=t.dataset.action;if(a==='logout')return logout();if(a==='reset')return reset();if(a==='warehouse-received')return warehouseAction('received');if(a==='warehouse-sent')return warehouseAction('sent');if(a==='open-camera')return startCamera();if(a==='demo-scan')return demoScan();if(a==='close-camera')return stopCamera();if(a==='unlock')return unlock();if(a==='export')return exportCsv();});
  function isSupportedScanner() { return 'BarcodeDetector' in window && navigator.mediaDevices?.getUserMedia; }
  async function startCamera(){try{requireRole('CUSTOMER_INCOMING');if(!isSupportedScanner())return lockReceipt('Scanner browser tidak tersedia. Gunakan Chrome Android terbaru untuk kamera scan.');const dialog=document.getElementById('cameraDialog');dialog.showModal();stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});const video=document.getElementById('cameraPreview');video.srcObject=stream;document.getElementById('cameraStatus').textContent='Arahkan kamera ke QR/barcode DN.';const detector=new BarcodeDetector({formats:['qr_code','code_128','code_39']});const scan=async()=>{if(!stream)return;try{const codes=await detector.detect(video);if(codes[0]){const value=codes[0].rawValue;stopCamera();if(value===state.order.dnCode)await captureLocation({source:'camera',barcode:value});else lockReceipt(`Barcode ${value} tidak sesuai dengan DN tujuan.`);return;}}catch{}requestAnimationFrame(scan)};requestAnimationFrame(scan);}catch(err){lockReceipt(`Kamera gagal atau izin ditolak: ${err.message||'unknown error'}`);stopCamera();}}
  function stopCamera(){if(stream){stream.getTracks().forEach(x=>x.stop());stream=null;}const d=document.getElementById('cameraDialog');if(d.open)d.close();}
  async function demoScan(){requireRole('CUSTOMER_INCOMING');toast('Demo scan ditandai sebagai simulasi. Memeriksa lokasi perangkat…');await captureLocation({source:'demo-simulation',barcode:state.order.dnCode});}
  async function captureLocation(scan){if(!navigator.geolocation)return lockReceipt('Location browser tidak tersedia.');try{const pos=await new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:12000,maximumAge:0}));const location={latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracy:pos.coords.accuracy,at:new Date().toISOString()};const distance=meters(location,state.customer);if(distance>state.customer.radiusMeters||location.accuracy>150)return lockReceipt(`Lokasi tidak sesuai: ${Math.round(distance)}m dari area customer, akurasi ${Math.round(location.accuracy)}m.`,location,scan);renderReceiptReady(location,scan);}catch(err){lockReceipt(`Lokasi gagal atau izin ditolak: ${err.message||'unknown error'}`,null,scan);}}
  function meters(a,b){const r=6371000,toRad=x=>x*Math.PI/180,dl=toRad(b.latitude-a.latitude),dn=toRad(b.longitude-a.longitude);const q=Math.sin(dl/2)**2+Math.cos(toRad(a.latitude))*Math.cos(toRad(b.latitude))*Math.sin(dn/2)**2;return 2*r*Math.atan2(Math.sqrt(q),Math.sqrt(1-q));}
  function renderReceiptReady(location,scan){const gate=document.getElementById('locationGate');if(gate)gate.innerHTML=badge('Location verified','green');const scanGate=document.getElementById('scanGate');if(scanGate)scanGate.innerHTML=badge(scan.source==='camera'?'Camera scan valid':'Demo scan marked','green');const confirm=document.getElementById('confirmGate');if(confirm)confirm.innerHTML=`<button class="button" data-action="confirm-receipt">Confirm receipt</button>`;document.addEventListener('click',function once(e){const t=e.target.closest('[data-action="confirm-receipt"]');if(!t)return;document.removeEventListener('click',once);confirmReceipt(location,scan);},{once:false});toast('All controls passed. Incoming PIC may confirm receipt.');}
  function confirmReceipt(location,scan){const u=requireRole('CUSTOMER_INCOMING'),o=state.order;if(o.receiptLock)return toast('DN masih locked.');if(o.status!=='SHIPMENT')return toast('DN tidak siap untuk receipt.');if(u.customerId!==o.customerId)return lockReceipt('Customer account does not match delivery destination.',location,scan);o.status='CUSTOMER_RECEIVED';addEvent('CUSTOMER_RECEIVED','Customer received confirmed after DN and location verification',{location,scanSource:scan.source});state.notifications.push({title:'Customer Receipt confirmed',message:`${o.dnCode} received by ${u.name} at ${new Date().toLocaleTimeString('id-ID')}`});save(state);toast('Customer Received recorded. Planner notified.');render();}
  function lockReceipt(reason,location=null,scan=null){const o=state.order;if(o.status==='CUSTOMER_RECEIVED')return toast('DN sudah received; tidak dapat dikunci ulang.');o.receiptLock={lockedAt:new Date().toISOString(),reason,actorId:me()?.id||'unknown',location,scan};addEvent('ABNORMALITY_LOCK','Customer receipt blocked',{reason,location,scanSource:scan?.source});save(state);toast('Receipt locked and abnormality recorded.');render();}
  function unlock(){requireRole('ADMIN');const reason=document.getElementById('recoveryReason')?.value.trim();if(!reason)return toast('Recovery reason wajib diisi.');const o=state.order;if(!o.receiptLock)return toast('Tidak ada lock untuk dibuka.');o.receiptLock.recoveredAt=new Date().toISOString();o.receiptLock.recoveredBy=me().id;o.receiptLock.recoveryReason=reason;addEvent('ADMIN_UNLOCK','Admin unlocked DN for re-verification',{reason});o.receiptLock=null;save(state);toast('DN unlocked. Incoming must verify again.');render();}
  function csvContent(events, o){const headers=['event_id','time','event_type','order','part_id','lot','dn','quantity','unit','status','pic','role','department','reason','location_result','demo_seed'];const rows=events.map(e=>[e.id,e.at,e.type,o.planNo,o.partId,o.lotId,o.dnCode,o.quantity,o.unit,o.status,e.actorName,e.role,e.department,e.reason||'',e.location?`${e.location.latitude},${e.location.longitude} ±${e.location.accuracy||''}`:'',e.demoSeed?'yes':'no']);return [headers,...rows].map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');}
  function exportCsv(){requireRole('ADMIN');const o=state.order;const blob=new Blob([csvContent(state.events,o)],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`MSC_Traceability_${o.dnCode}.csv`;a.click();URL.revokeObjectURL(url);toast('CSV report downloaded.');}
  window.MSC_TEST={seed,meters,csvContent,roleCan:(role,view)=>allowed[role]?.includes(view),validateReceipt:(sample)=>{const s=seed(),o=s.order;if(sample.role!=='CUSTOMER_INCOMING')return 'ROLE_REJECT';if(sample.customerId!==o.customerId)return 'CUSTOMER_REJECT';if(o.status!=='SHIPMENT')return 'STATUS_REJECT';if(o.receiptLock)return 'LOCK_REJECT';if(sample.barcode!==o.dnCode)return 'BARCODE_REJECT';if(!sample.location)return 'LOCATION_REJECT';return meters(sample.location,s.customer)<=s.customer.radiusMeters&&sample.location.accuracy<=150?'PASS':'LOCATION_REJECT';}};
  render();
})();
