/* MSC Traceability POC — browser-local demo, not a production audit system. */
(function () {
  const STORAGE = 'msc-traceability-poc-v2';
  const SESSION = 'msc-traceability-session-v2';
  const users = [
    { id:'planner', username:'planner', password:'demo123', name:'Rina Planner', role:'PLANNER', department:'PPIC' },
    { id:'warehouse', username:'warehouse', password:'demo123', name:'Doni Warehouse', role:'WAREHOUSE', department:'Warehouse' },
    { id:'prepare', username:'prepare', password:'demo123', name:'Sari Prepare', role:'PREPARE', department:'Material Prepare' },
    { id:'mca', username:'mca', password:'demo123', name:'Bima MC A', role:'MC_A', department:'Production' },
    { id:'mcb', username:'mcb', password:'demo123', name:'Citra MC B', role:'MC_B', department:'Production' },
    { id:'mcc', username:'mcc', password:'demo123', name:'Dewa MC C', role:'MC_C', department:'Production' },
    { id:'quality', username:'quality', password:'demo123', name:'Nina Quality', role:'QUALITY', department:'Final Inspection' },
    { id:'incoming', username:'incoming', password:'demo123', name:'Maya Incoming', role:'CUSTOMER_INCOMING', department:'Customer Incoming', customerId:'cus-01' },
    { id:'admin', username:'admin', password:'demo123', name:'Adit Admin', role:'ADMIN', department:'System Control' }
  ];
  const roles = { PLANNER:'Planner / PPIC', WAREHOUSE:'Warehouse PIC', PREPARE:'Prepare PIC', MC_A:'Operator MC A', MC_B:'Operator MC B', MC_C:'Operator MC C', QUALITY:'Final Inspection', CUSTOMER_INCOMING:'Customer Incoming', ADMIN:'Admin' };
  const steps = [
    { id:'PLAN_RELEASED', label:'Plan Released', role:'PLANNER', scan:'plan', description:'PPIC merilis plan produksi.' },
    { id:'MATERIAL_REQUESTED', label:'Raw Material Request', role:'PLANNER', scan:'part', description:'PPIC membuat request material.' },
    { id:'RAW_MATERIAL_RECEIVED', label:'Raw Material Received', role:'WAREHOUSE', scan:'part', description:'Warehouse scan material sebelum diserahkan.' },
    { id:'MATERIAL_PREPARED', label:'Material Prepared', role:'PREPARE', scan:'part', description:'Prepare PIC memastikan part dan lot sesuai.' },
    { id:'MC_A_COMPLETE', label:'MC A Complete', role:'MC_A', scan:'part', description:'Operator scan lot setelah proses MC A.' },
    { id:'MC_B_COMPLETE', label:'MC B Complete', role:'MC_B', scan:'part', description:'Operator scan lot setelah proses MC B.' },
    { id:'MC_C_COMPLETE', label:'MC C Complete', role:'MC_C', scan:'part', description:'Operator scan lot setelah proses MC C.' },
    { id:'FINAL_INSPECTION_PASS', label:'Final Inspection Pass', role:'QUALITY', scan:'part', description:'Quality scan dan meluluskan final inspection.' },
    { id:'FINISHED_GOODS_RECEIVED', label:'Finished Good Received', role:'WAREHOUSE', scan:'part', description:'Warehouse scan finished good.' },
    { id:'DN_RELEASED', label:'Delivery Note Released', role:'PLANNER', scan:'dn', description:'PPIC merilis Delivery Note.' },
    { id:'SHIPMENT_SENT', label:'Shipment Sent', role:'WAREHOUSE', scan:'dn', description:'Warehouse scan DN saat milkrun/shipment.' },
    { id:'CUSTOMER_RECEIVED', label:'Customer Received', role:'CUSTOMER_INCOMING', scan:'dn-location', description:'Customer Incoming scan DN dan validasi GPS.' }
  ];
  const app = document.getElementById('app');
  let stream = null;
  function uid() { return (crypto && crypto.randomUUID) ? crypto.randomUUID() : 'evt-'+Date.now(); }
  function seed() { return { order:{ planNo:'PLAN-2026-091', partId:'A-LED-001', partName:'Smart Headlamp Module', lotId:'LOT-2409-A', quantity:120, unit:'pcs', dnCode:'DN-2409-001', customerName:'SEMV Demo Plant', status:'WAITING_PLAN', cursor:0, lock:null }, customer:{ id:'cus-01', latitude:-6.3764484, longitude:107.3181421, radiusMeters:250 }, events:[], notifications:[] }; }
  function load() { try { const v=JSON.parse(localStorage.getItem(STORAGE)); return v && v.order && Array.isArray(v.events) ? v : seed(); } catch(e) { return seed(); } }
  let state=load(), session=JSON.parse(localStorage.getItem(SESSION)||'null'), page='tracking';
  function save(){ localStorage.setItem(STORAGE,JSON.stringify(state)); }
  function me(){ return users.find(function(u){ return u.id===(session&&session.userId); }); }
  function esc(v){ return String(v==null?'':v).replace(/[&<>"']/g,function(c){ return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]; }); }
  function time(v){ return new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)); }
  function active(){ return steps[state.order.cursor] || null; }
  function expected(step){ return step.scan==='plan' ? state.order.planNo : step.scan==='part' ? state.order.partId+'|'+state.order.lotId : state.order.dnCode; }
  function addEvent(type,message,extra){ const u=me()||{id:'system',name:'System',role:'SYSTEM',department:'System'}; state.events.push(Object.assign({id:uid(),type:type,message:message,at:new Date().toISOString(),actorName:u.name,role:u.role,department:u.department,partId:state.order.partId,lotId:state.order.lotId,dnCode:state.order.dnCode},extra||{})); save(); }
  function login(username,password){ const user=users.find(function(u){ return u.username===username&&u.password===password; }); if(!user) return toast('Username atau password tidak sesuai.'); session={userId:user.id}; localStorage.setItem(SESSION,JSON.stringify(session)); page='tracking'; render(); }
  function logout(){ session=null; localStorage.removeItem(SESSION); render(); }
  function reset(){ if(!confirm('Reset seluruh transaksi traceability di browser ini?')) return; state=seed(); save(); render(); }
  function render(){ const user=me(); if(!user) return loginView(); app.innerHTML='<div class="app-shell"><aside class="sidebar"><div class="logo">MSC Trace<small>REAL TRANSACTION POC</small></div><div class="profile"><b>'+esc(user.name)+'</b><span>'+esc(roles[user.role])+' · '+esc(user.department)+'</span></div><nav class="nav"><button class="'+(page==='tracking'?'active':'')+'" data-page="tracking">Traceability Flow</button><button class="'+(page==='task'?'active':'')+'" data-page="task">My Scan Task</button>'+(user.role==='ADMIN'?'<button class="'+(page==='admin'?'active':'')+'" data-page="admin">Abnormality Lock</button><button class="'+(page==='report'?'active':'')+'" data-page="report">Report CSV</button>':'')+'</nav><div class="side-bottom"><button data-action="reset">Reset Demo</button><button data-action="logout">Keluar</button></div></aside><main class="main"><header class="topbar"><div><h1>'+title()+'</h1><p>'+esc(user.name)+' · '+esc(roles[user.role])+'</p></div>'+badge()+'</header><section class="content">'+view()+'</section></main></div>'; }
  function title(){ return page==='task'?'My Scan Task':page==='admin'?'Abnormality & Recovery':page==='report'?'Report Evidence':'Traceability Flow'; }
  function badge(){ const o=state.order; if(o.lock) return '<span class="status red">! LOCKED</span>'; if(!active()) return '<span class="status green">✓ CUSTOMER RECEIVED</span>'; return '<span class="status blue">• '+esc(active().label)+'</span>'; }
  function loginView(){ app.innerHTML='<main class="login"><section class="login-card"><div class="brand"><div class="eyebrow">After Project · MSC</div><h1>Trace every handoff.</h1><p>Setiap tahap wajib scan oleh PIC yang berwenang. Tahap berikutnya tidak bisa bergerak sebelum bukti scan valid.</p><p><small>Data POC disimpan di browser ini.</small></p></div><div class="login-form"><h2>Masuk sebagai PIC</h2><form id="loginForm"><div class="field"><label>Username</label><input name="username" required></div><div class="field"><label>Password</label><input name="password" type="password" required></div><button class="button wide">Masuk</button></form><div class="demo-users">'+users.map(function(u){return '<button data-demo-user="'+u.username+'"><b>'+esc(roles[u.role])+'</b><small>'+u.username+' / demo123</small></button>';}).join('')+'</div></div></section></main>'; }
  function view(){ if(page==='task') return taskView(); if(page==='admin') return adminView(); if(page==='report') return reportView(); return trackingView(); }
  function orderFacts(){ const o=state.order; return '<div class="facts"><div class="fact"><small>Plan</small><b>'+esc(o.planNo)+'</b></div><div class="fact"><small>Part / Lot</small><b>'+esc(o.partId)+' · '+esc(o.lotId)+'</b></div><div class="fact"><small>Qty</small><b>'+o.quantity+' '+esc(o.unit)+'</b></div><div class="fact"><small>DN</small><b>'+esc(o.dnCode)+'</b></div></div>'; }
  function trackingView(){ const next=active(); return '<article class="card"><div class="order-head"><div><div class="role-label">One scanned Lot</div><h2>'+esc(state.order.partName)+'</h2><p class="muted">Barcode part: <b>'+esc(state.order.partId+'|'+state.order.lotId)+'</b> · DN: <b>'+esc(state.order.dnCode)+'</b></p></div>'+badge()+'</div>'+orderFacts()+'</article><div class="grid two" style="margin-top:18px"><article class="card"><div class="role-label">End-to-end evidence</div><h2>Traceability stages</h2><ol class="timeline">'+steps.map(function(s,i){ const done=i<state.order.cursor,now=i===state.order.cursor; return '<li><span class="dot '+(done?'good':now?'admin':'')+'"></span><div><b>'+esc(s.label)+'</b><small>'+esc(s.description)+' · PIC: '+esc(roles[s.role])+'</small></div><time>'+(done?time(state.events.filter(function(e){return e.type===s.id;}).slice(-1)[0].at):now?'Waiting scan':'Locked by sequence')+'</time></li>'; }).join('')+'</ol></article><aside class="card"><div class="role-label">Current transaction</div><h2>'+esc(next?next.label:'Flow complete')+'</h2><p class="muted">'+esc(next?next.description:'Customer receipt sudah terbukti.')+'</p>'+(state.order.lock?'<div class="notice bad"><b>Flow locked</b><p>'+esc(state.order.lock.reason)+'</p></div>':'<div class="notice good"><b>Sequential control active</b><p>Hanya PIC '+esc(next?roles[next.role]:'-')+' dapat menjalankan langkah ini.</p></div>')+'</aside></div>'; }
  function taskView(){ const user=me(), step=active(); if(!step) return '<article class="card"><h2>Flow completed</h2><p class="muted">Customer Received sudah tercatat. Tidak ada transaksi kedua untuk DN ini.</p></article>'; if(state.order.lock) return '<article class="card"><div class="notice bad"><b>Transaction blocked</b><p>'+esc(state.order.lock.reason)+'</p></div><p class="muted">Hanya Admin dapat membuka kembali transaksi, dengan alasan recovery tercatat.</p></article>'; if(step.role!==user.role) return '<article class="card"><div class="role-label">Role boundary</div><h2>Menunggu '+esc(roles[step.role])+'</h2><p class="muted">Tahap aktif: '+esc(step.label)+'. Akun ini tidak memiliki otoritas untuk scan pada tahap tersebut.</p></article>'; const code=expected(step); return '<article class="card"><div class="role-label">Authorized transaction</div><h2>'+esc(step.label)+'</h2><p>'+esc(step.description)+'</p>'+orderFacts()+'<div class="receipt-gate"><div class="gate-row"><b>Expected scan</b><span>'+esc(code)+'</span></div><div class="gate-row"><b>PIC</b><span>'+esc(user.name)+'</span></div><div class="gate-row"><b>Trigger</b><span>Camera scan or marked simulation</span></div></div><div class="actions"><button class="button" data-action="open-camera">Scan with camera</button><button class="button secondary" data-action="demo-scan">Run marked demo scan</button></div><p class="muted"><small>Simulation remains labelled in the event history. For Customer Received, GPS must still pass.</small></p></article>'; }
  function adminView(){ if(me().role!=='ADMIN') return '<article class="card"><p>Akses ditolak.</p></article>'; const lock=state.order.lock; return '<article class="card"><div class="role-label">Admin boundary</div><h2>'+ (lock?'Unlock blocked flow':'No active lock')+'</h2>'+(lock?'<div class="notice bad"><b>'+esc(lock.step)+'</b><p>'+esc(lock.reason)+'</p></div><div class="field"><label>Recovery reason (required)</label><textarea id="recoveryReason" rows="3" placeholder="Jelaskan alasan PIC boleh mencoba scan ulang"></textarea></div><button class="button" data-action="unlock">Unlock for re-scan</button>':'<div class="notice good"><b>No abnormality</b><p>Admin cannot execute production or customer scans.</p></div>')+'</article>'; }
  function reportView(){ if(me().role!=='ADMIN') return '<article class="card"><p>Akses ditolak.</p></article>'; return '<article class="card"><div class="order-head"><div><div class="role-label">Audit evidence</div><h2>Transaction report</h2><p class="muted">Includes every PIC, scan source, rejection, lock and unlock.</p></div><button class="button" data-action="export">Download CSV</button></div><div class="table-wrap"><table class="report-table"><thead><tr><th>Time</th><th>Event</th><th>PIC</th><th>Role</th><th>Scan</th><th>Reason</th></tr></thead><tbody>'+state.events.slice().reverse().map(function(e){return '<tr><td>'+time(e.at)+'</td><td>'+esc(e.type)+'</td><td>'+esc(e.actorName)+'</td><td>'+esc(roles[e.role]||e.role)+'</td><td>'+esc(e.scanSource||'—')+'</td><td>'+esc(e.reason||'—')+'</td></tr>';}).join('')+'</tbody></table></div></article>'; }
  function startCamera(){ const step=active(), user=me(); if(!step||step.role!==user.role) return toast('Akses scan ditolak.'); if(!('BarcodeDetector' in window)||!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia) return lock('Browser scanner tidak tersedia. Gunakan Chrome Android terbaru atau demo scan.'); const dialog=document.getElementById('cameraDialog'); dialog.querySelector('strong').textContent='Scan '+step.label; dialog.showModal(); navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}}).then(function(s){ stream=s; const video=document.getElementById('cameraPreview'); video.srcObject=s; document.getElementById('cameraStatus').textContent='Arahkan kamera ke barcode '+expected(step); const detector=new BarcodeDetector({formats:['qr_code','code_128','code_39']}); function read(){ if(!stream) return; detector.detect(video).then(function(codes){ if(codes[0]){ stopCamera(); scanned(step,codes[0].rawValue,'camera'); } else requestAnimationFrame(read); }).catch(function(){ requestAnimationFrame(read); }); } requestAnimationFrame(read); }).catch(function(err){ lock('Camera failed or permission denied: '+(err.message||'unknown')); stopCamera(); }); }
  function stopCamera(){ if(stream){ stream.getTracks().forEach(function(t){t.stop();}); stream=null; } const d=document.getElementById('cameraDialog'); if(d.open) d.close(); }
  function demoScan(){ const step=active(),user=me(); if(!step||step.role!==user.role) return toast('Akses scan ditolak.'); scanned(step,expected(step),'demo-simulation'); }
  function scanned(step,value,source){ if(value!==expected(step)) return lock('Barcode mismatch. Expected '+expected(step)+', read '+value+'.',{scanSource:source,barcode:value}); if(step.scan==='dn-location') return captureLocation(step,source); complete(step,source,null); }
  function captureLocation(step,source){ if(!navigator.geolocation) return lock('Browser location tidak tersedia.',{scanSource:source}); toast('DN valid. Memeriksa GPS perangkat…'); navigator.geolocation.getCurrentPosition(function(pos){ const loc={latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracy:pos.coords.accuracy}; const d=meters(loc,state.customer); if(d>state.customer.radiusMeters||loc.accuracy>150) return lock('Location rejected: '+Math.round(d)+'m from customer area, accuracy '+Math.round(loc.accuracy)+'m.',{scanSource:source,location:loc}); complete(step,source,loc); },function(err){ lock('Location failed or permission denied: '+(err.message||'unknown'),{scanSource:source}); },{enableHighAccuracy:true,timeout:12000,maximumAge:0}); }
  function complete(step,source,location){ if(active()!==step) return; state.order.cursor++; state.order.status=state.order.cursor===steps.length?'CUSTOMER_RECEIVED':steps[state.order.cursor].id; addEvent(step.id,step.label+' confirmed',{scanSource:source,location:location}); if(step.id==='CUSTOMER_RECEIVED') state.notifications.push({title:'Customer Received',message:state.order.dnCode+' accepted by Customer Incoming.'}); save(); toast(step.label+' recorded.'); render(); }
  function lock(reason,extra){ if(state.order.status==='CUSTOMER_RECEIVED') return toast('DN sudah selesai.'); const step=active(); state.order.lock={step:step?step.id:'UNKNOWN',reason:reason,at:new Date().toISOString()}; addEvent('ABNORMALITY_LOCK','Transaction blocked',Object.assign({reason:reason},extra||{})); save(); toast('Transaction blocked. Admin review required.'); render(); }
  function unlock(){ if(me().role!=='ADMIN') return; const r=document.getElementById('recoveryReason'); const reason=r&&r.value.trim(); if(!reason) return toast('Recovery reason wajib diisi.'); if(!state.order.lock) return; addEvent('ADMIN_UNLOCK','Admin unlocked for re-scan',{reason:reason}); state.order.lock=null; save(); toast('Unlocked. PIC must scan again.'); render(); }
  function meters(a,b){ const r=6371000,q=Math.PI/180,dl=(b.latitude-a.latitude)*q,dn=(b.longitude-a.longitude)*q,x=Math.sin(dl/2)*Math.sin(dl/2)+Math.cos(a.latitude*q)*Math.cos(b.latitude*q)*Math.sin(dn/2)*Math.sin(dn/2); return 2*r*Math.atan2(Math.sqrt(x),Math.sqrt(1-x)); }
  function csv(){ const h=['time','event','pic','role','department','scan_source','reason','part_id','lot_id','dn']; const rows=state.events.map(function(e){return [e.at,e.type,e.actorName,e.role,e.department,e.scanSource||'',e.reason||'',e.partId,e.lotId,e.dnCode];}); return [h].concat(rows).map(function(r){return r.map(function(v){return '"'+String(v).replaceAll('"','""')+'"';}).join(',');}).join('\n'); }
  function exportCsv(){ const a=document.createElement('a'),url=URL.createObjectURL(new Blob([csv()],{type:'text/csv;charset=utf-8'})); a.href=url;a.download='MSC_Traceability_'+state.order.dnCode+'.csv';a.click();URL.revokeObjectURL(url);toast('CSV report downloaded.'); }
  function toast(msg){ const old=document.querySelector('.toast');if(old)old.remove();const x=document.createElement('div');x.className='toast';x.textContent=msg;document.body.append(x);setTimeout(function(){x.remove();},3500); }
  document.addEventListener('submit',function(e){ if(e.target.id==='loginForm'){ e.preventDefault();const f=new FormData(e.target);login(f.get('username'),f.get('password')); } });
  document.addEventListener('click',function(e){ const t=e.target.closest('button');if(!t)return;if(t.dataset.page){page=t.dataset.page;render();return;}if(t.dataset.demoUser){login(t.dataset.demoUser,'demo123');return;}const a=t.dataset.action;if(a==='logout')logout();if(a==='reset')reset();if(a==='open-camera')startCamera();if(a==='demo-scan')demoScan();if(a==='close-camera')stopCamera();if(a==='unlock')unlock();if(a==='export')exportCsv(); });
  window.MSC_TEST={seed:seed,meters:meters,steps:steps};
  render();
})();